name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # 注意：只有當 package-lock.json 存在時才啟用 cache
          # 如果沒有 lock 文件，請移除下面這行
          # cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
        continue-on-error: true  # 允許 lint 警告不中斷構建
        
      - name: Format check
        run: npm run format:check
        continue-on-error: true  # 允許格式檢查警告不中斷構建
      
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
      
      # 為 SPA 創建 404.html 以支援路由刷新
      - name: Create 404.html for SPA routing
        run: cp dist/index.html dist/404.html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}\
    
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: deploy-pages@v4
